pipeline:
  build:
    image: alpine:3.15
    commands:
      - apk --update add ansible
      - ansible-galaxy collection build
    
  sanity:
    image: alpine:3.15
    commands:
      - apk --update add ansible py3-requests py3-pycodestyle py3-pylint py3-voluptuous yamllint
      - mkdir -p /ansible_collections/markuman/devops
      - mkdir -p /root/.cache/pylint
      - cp -a * /ansible_collections/markuman/devops
      - cd /ansible_collections/markuman/devops && ansible-test sanity --python 3.9
 